import 'package:flutter/material.dart';

IconData iconFromString(String name) {
  final icons = <String, IconData>{
    // ── Finance / Income ──────────────────────────────────────────
    'salary': Icons.account_balance_outlined,
    'wage': Icons.account_balance_outlined,
    'payroll': Icons.account_balance_outlined,
    'freelance': Icons.computer_outlined,
    'contract': Icons.description_outlined,
    'investment': Icons.trending_up_outlined,
    'dividend': Icons.monetization_on_outlined,
    'interest': Icons.percent_outlined,
    'rental': Icons.home_work_outlined,
    'gift': Icons.card_giftcard_outlined,
    'refund': Icons.replay_outlined,
    'bonus': Icons.star_outline,
    'commission': Icons.handshake_outlined,
    'allowance': Icons.account_balance_wallet_outlined,

    // ── Food & Dining ─────────────────────────────────────────────
    'restaurant': Icons.restaurant_outlined,
    'food': Icons.restaurant_outlined,
    'dining': Icons.restaurant_outlined,
    'lunch': Icons.restaurant_outlined,
    'dinner': Icons.restaurant_outlined,
    'breakfast': Icons.free_breakfast_outlined,
    'coffee': Icons.local_cafe_outlined,
    'cafe': Icons.local_cafe_outlined,
    'grocery': Icons.shopping_cart_outlined,
    'groceries': Icons.shopping_cart_outlined,
    'supermarket': Icons.store_outlined,
    'fastfood': Icons.fastfood_outlined,
    'burger': Icons.lunch_dining_outlined,
    'pizza': Icons.local_pizza_outlined,
    'alcohol': Icons.local_bar_outlined,
    'bar': Icons.local_bar_outlined,
    'beer': Icons.sports_bar_outlined,
    'wine': Icons.wine_bar_outlined,
    'dessert': Icons.icecream_outlined,
    'bakery': Icons.bakery_dining_outlined,
    'delivery': Icons.delivery_dining_outlined,
    'takeout': Icons.takeout_dining_outlined,

    // ── Transport ─────────────────────────────────────────────────
    'car': Icons.directions_car_outlined,
    'auto': Icons.directions_car_outlined,
    'transport': Icons.directions_bus_outlined,
    'transit': Icons.directions_bus_outlined,
    'bus': Icons.directions_bus_outlined,
    'fuel': Icons.local_gas_station_outlined,
    'gas': Icons.local_gas_station_outlined,
    'gasoline': Icons.local_gas_station_outlined,
    'parking': Icons.local_parking_outlined,
    'taxi': Icons.local_taxi_outlined,
    'travel': Icons.flight_takeoff_outlined,
    'flight': Icons.flight_outlined,
    'train': Icons.train_outlined,
    'bicycle': Icons.directions_bike_outlined,
    'bike': Icons.directions_bike_outlined,
    'motorcycle': Icons.motorcycle_outlined,
    'boat': Icons.sailing_outlined,
    'ship': Icons.directions_boat_outlined,
    'toll': Icons.toll_outlined,
    'maintenance': Icons.build_outlined,

    // ── Shopping ──────────────────────────────────────────────────
    'shopping': Icons.shopping_bag_outlined,
    'retail': Icons.storefront_outlined,
    'clothes': Icons.checkroom_outlined,
    'fashion': Icons.checkroom_outlined,
    'electronics': Icons.laptop_outlined,
    'tech': Icons.smartphone_outlined,
    'computer': Icons.computer_outlined,
    'phone': Icons.phone_iphone_outlined,
    'mobile': Icons.phone_android_outlined,
    'books': Icons.menu_book_outlined,
    'gifts': Icons.card_giftcard_outlined,
    'online': Icons.add_shopping_cart_outlined,
    'marketplace': Icons.store_outlined,
    'decor': Icons.chair_outlined,
    'furniture': Icons.chair_outlined,
    'tools': Icons.handyman_outlined,

    // ── Housing & Utilities ───────────────────────────────────────
    'home': Icons.home_outlined,
    'housing': Icons.home_outlined,
    'house': Icons.home_outlined,
    'rent': Icons.house_outlined,
    'mortgage': Icons.home_work_outlined,
    'electricity': Icons.bolt_outlined,
    'power': Icons.bolt_outlined,
    'water': Icons.water_drop_outlined,
    'internet': Icons.wifi_outlined,
    'naturalgas': Icons.local_fire_department_outlined,
    'utilities': Icons.plumbing_outlined,
    'repair': Icons.build_outlined,
    'renovation': Icons.construction_outlined,
    'cleaning': Icons.cleaning_services_outlined,
    'security': Icons.shield_outlined,
    'insurance': Icons.verified_user_outlined,

    // ── Health ────────────────────────────────────────────────────
    'health': Icons.favorite_outline,
    'medical': Icons.medical_services_outlined,
    'pharmacy': Icons.local_pharmacy_outlined,
    'medicine': Icons.medication_outlined,
    'doctor': Icons.medical_services_outlined,
    'hospital': Icons.local_hospital_outlined,
    'dental': Icons.medical_services_outlined,
    'fitness': Icons.fitness_center_outlined,
    'gym': Icons.fitness_center_outlined,
    'eye': Icons.visibility_outlined,
    'therapy': Icons.psychology_outlined,

    // ── Entertainment ─────────────────────────────────────────────
    'entertainment': Icons.movie_outlined,
    'movies': Icons.movie_creation_outlined,
    'cinema': Icons.theaters_outlined,
    'music': Icons.music_note_outlined,
    'concert': Icons.music_note_outlined,
    'games': Icons.sports_esports_outlined,
    'gaming': Icons.sports_esports_outlined,
    'sports': Icons.sports_soccer_outlined,
    'hobby': Icons.palette_outlined,
    'streaming': Icons.live_tv_outlined,
    'tickets': Icons.confirmation_number_outlined,
    'museum': Icons.museum_outlined,
    'park': Icons.park_outlined,
    'vacation': Icons.beach_access_outlined,

    // ── Education ─────────────────────────────────────────────────
    'education': Icons.school_outlined,
    'school': Icons.school_outlined,
    'university': Icons.account_balance_outlined,
    'college': Icons.school_outlined,
    'course': Icons.class_outlined,
    'tuition': Icons.payments_outlined,
    'library': Icons.local_library_outlined,
    'training': Icons.co_present_outlined,

    // ── Personal ──────────────────────────────────────────────────
    'family': Icons.people_outlined,
    'children': Icons.child_care_outlined,
    'baby': Icons.child_care_outlined,
    'pet': Icons.pets_outlined,
    'dog': Icons.pets_outlined,
    'cat': Icons.pets_outlined,
    'charity': Icons.volunteer_activism_outlined,
    'donation': Icons.volunteer_activism_outlined,
    'beauty': Icons.spa_outlined,
    'hair': Icons.content_cut_outlined,
    'barber': Icons.content_cut_outlined,
    'laundry': Icons.local_laundry_service_outlined,
    'selfcare': Icons.self_improvement_outlined,
    'cosmetics': Icons.spa_outlined,

    // ── Business & Work ───────────────────────────────────────────
    'business': Icons.business_outlined,
    'work': Icons.work_outline,
    'office': Icons.business_outlined,
    'supplies': Icons.inventory_2_outlined,
    'software': Icons.code_outlined,
    'services': Icons.miscellaneous_services_outlined,
    'consulting': Icons.group_work_outlined,
    'marketing': Icons.campaign_outlined,

    // ── Other ─────────────────────────────────────────────────────
    'subscription': Icons.subscriptions_outlined,
    'tax': Icons.request_quote_outlined,
    'bank': Icons.account_balance_outlined,
    'transfer': Icons.swap_horiz_outlined,
    'fee': Icons.money_off_outlined,
    'fine': Icons.gavel_outlined,
    'loan': Icons.savings_outlined,
    'savings': Icons.savings_outlined,
    'wallet': Icons.wallet_outlined,
    'cash': Icons.money_outlined,
    'atm': Icons.atm_outlined,
    'coins': Icons.payments_outlined,
    'exchange': Icons.currency_exchange_outlined,
    'default': Icons.category_outlined,
  };

  final key = name.toLowerCase().replaceAll('_', '').replaceAll('-', '');
  return icons.entries
      .firstWhere(
        (e) => e.key == key || key.contains(e.key),
        orElse: () => const MapEntry('default', Icons.category_outlined),
      )
      .value;
}
